### ISSUE TITLE
[Feature] method/ function to make a vanilla copy of the stack

### ISSUE THREAD

**Issue by Cheukting** [picknmix/picknmix#38]
### Description

Provide a method/ function to make a vanilla copy of the stack built (only model architectures, no trained models)

Should not be too complicated, medium level difficulty.

**Comment by ipacheco-uy** [comment]
I will try this in the weekend, do you have any place in mind to leave this function/method?

**Comment by Cheukting** [comment]
If you could implement it as methods for Stack and Layer (they should be fairly similar), it's amazing. Example usage would be:

```
some_model = Stack(...)
some_model.fit(...)
new_clone_model = some_model.copy()
# new_clone_model would be a new model with the same structure as some_model
# it is identical to some_model BEFORE it was trained.
```

 Let me know if you have other questions! Thanks again.

**Comment by Cheukting** [comment]
Thanks @TenebraeX8 we can close this for now, when we are working on #32 we will have to support this for Keras models as well.
