### ISSUE TITLE
[Doc] putting quick start quide on README.md

### ISSUE THREAD

**Issue by Cheukting** [picknmix/picknmix#52]
In README.md, adding simple instruction about how to pip install picknmix and a couple of example for the usage.

**Comment by N1ghtCrawl3r** [comment]
I can do this. Can I use the same examples for usage given in the documentation?

**Comment by Cheukting** [comment]
Sure @N1ghtCrawl3r ! It's a good idea. But we want to keep the example short. So maybe 1 or 2 basic usage example.

**Comment by N1ghtCrawl3r** [comment]
Okay! I am working on it.

**Comment by Cheukting** [comment]
Closing this by #57
