### ISSUE TITLE
Can we use codecov.io for test coverage

### ISSUE THREAD

**Issue by Cheukting** [picknmix/picknmix#68]
* Pick n Mix version: 0.1.3

### Description

Right now we use coverage and run it in Travis to see test coverage. However, you have to dig in the log to see the coverage which is not convenient for all contributors. One seems to be good CI tool is https://codecov.io which you can add the badge on the README so users and contributors can see the coverage openly.

Steps:
1) Apply codecov.io following their documentation
2) remove direct coverage form the travis yml, call it form tox

**Comment by neomatrix369** [comment]
Will it still be possible to run coverage in offline mode (from CLI on local machine)?

If I were you I would preserve offline alternatives, so that developers can run coverage checks during their development work (ones who practise TDD might want to use it).

Just my thinking.

**Comment by Cheukting** [comment]
you could run it in tox

**Comment by Cheukting** [comment]
I have merged PR for this. Though GitHub is not showing Travis build at the moment (don't know why) you can see the built on Travis's page and it works fine. Will have to investigate on GitHub's side
