### ISSUE TITLE
[Doc] Improve CONTRIBUTING.rst for Documentation contribution

### ISSUE THREAD

**Issue by Cheukting** [picknmix/picknmix#73]
* Pick n Mix version: 0.1.3

### Description

In [Write Documentation](https://github.com/picknmix/picknmix/blob/master/CONTRIBUTING.rst#write-documentation)
mention that if no code change, CI testing is not required and they can write `[skip CI]` in the commit message to skip the time taken for CI builds. You can referer to [Travis](https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build) for more info.

**Comment by nasanos** [comment]
I can handle this, if no one else has started on it.

**Comment by FarhanMuftiHilmy** [comment]
give me a try @Cheukting
