### ISSUE TITLE
[Doc] 2 things to improve CONTRIBUTING.rst

### ISSUE THREAD

**Issue by Cheukting** [picknmix/picknmix#74]
### Description

2 things to improve [CONTRIBUTING.rst](https://github.com/picknmix/picknmix/blob/master/CONTRIBUTING.rst):

1) Remove the section [Tips](https://github.com/picknmix/picknmix/blob/master/CONTRIBUTING.rst#tips) as it is not relevant at all.

2) make a table of content at the beginning for easy access to different sections. You can refere to this tutorial about [RST](https://www.devdungeon.com/content/restructuredtext-rst-tutorial-0#create-a-basic-rst-document)

**Comment by FarazFe** [comment]
@Cheukting If I remember correctly, the documents listed in the toctree should be located in the same directory as the index file, so what do you propose?
I think restructuring the doc directory could work.

**Comment by Cheukting** [comment]
@FarazFe I think I didn't make it clear here, my bad. I have only done it with my other project before with md files. Basically I want a list at the beginning of the file so people can click and jump to different sections of the file. Example [here](https://github.com/Cheukting/rasa_workshop/blob/master/README.md)

**Comment by FarazFe** [comment]
@Cheukting You want CONTRIBUTING.rst to be like this, right?

![Screenshot from 2019-10-19 00-55-57](https://user-images.githubusercontent.com/15348844/67129430-7ef41c00-f20b-11e9-8ebe-883cbf83463e.png)

Then again if I recall correctly, the picknmix/CONTRIBUTING.rst should be in the same directory as docs/contributing.rst so the toctree works.

**Comment by Cheukting** [comment]
I am not that familiar with toctree but sure if you want to give it a try. :-)
